/*
 almond 0.3.0 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/almond for details
*/
var requirejs,require,define;
(function(i){function q(a,b){var c,n,f,h,d,e,k,l,i,o=b&&b.split("/"),g=j.map,m=g&&g["*"]||{};if(a&&"."===a.charAt(0))if(b){o=o.slice(0,o.length-1);a=a.split("/");d=a.length-1;j.nodeIdCompat&&v.test(a[d])&&(a[d]=a[d].replace(v,""));a=o.concat(a);for(d=0;d<a.length;d+=1)if(c=a[d],"."===c)a.splice(d,1),d-=1;else if(".."===c)if(1===d&&(".."===a[2]||".."===a[0]))break;else 0<d&&(a.splice(d-1,2),d-=2);a=a.join("/")}else 0===a.indexOf("./")&&(a=a.substring(2));if((o||m)&&g){c=a.split("/");for(d=c.length;0<
d;d-=1){n=c.slice(0,d).join("/");if(o)for(i=o.length;0<i;i-=1)if(f=g[o.slice(0,i).join("/")])if(f=f[n]){h=f;e=d;break}if(h)break;!k&&(m&&m[n])&&(k=m[n],l=d)}!h&&k&&(h=k,e=l);h&&(c.splice(0,e,h),a=c.join("/"))}return a}function w(a,b){return function(){var c=y.call(arguments,0);"string"!==typeof c[0]&&1===c.length&&c.push(null);return g.apply(i,c.concat([a,b]))}}function z(a){return function(b){return q(b,a)}}function A(a){return function(b){e[a]=b}}function r(a){if(l.call(m,a)){var b=m[a];delete m[a];
t[a]=!0;s.apply(i,b)}if(!l.call(e,a)&&!l.call(t,a))throw Error("No "+a);return e[a]}function x(a){var b,c=a?a.indexOf("!"):-1;-1<c&&(b=a.substring(0,c),a=a.substring(c+1,a.length));return[b,a]}var s,g,u,p,e={},m={},j={},t={},l=Object.prototype.hasOwnProperty,y=[].slice,v=/\.js$/;u=function(a,b){var c,e=x(a),f=e[0],a=e[1];f&&(f=q(f,b),c=r(f));f?a=c&&c.normalize?c.normalize(a,z(b)):q(a,b):(a=q(a,b),e=x(a),f=e[0],a=e[1],f&&(c=r(f)));return{f:f?f+"!"+a:a,n:a,pr:f,p:c}};p={require:function(a){return w(a)},
exports:function(a){var b=e[a];return"undefined"!==typeof b?b:e[a]={}},module:function(a){return{id:a,uri:"",exports:e[a],config:function(){return j&&j.config&&j.config[a]||{}}}}};s=function(a,b,c,n){var f,h,d,g,k=[];h=typeof c;var j,n=n||a;if("undefined"===h||"function"===h){b=!b.length&&c.length?["require","exports","module"]:b;for(g=0;g<b.length;g+=1)if(d=u(b[g],n),h=d.f,"require"===h)k[g]=p.require(a);else if("exports"===h)k[g]=p.exports(a),j=!0;else if("module"===h)f=k[g]=p.module(a);else if(l.call(e,
h)||l.call(m,h)||l.call(t,h))k[g]=r(h);else if(d.p)d.p.load(d.n,w(n,!0),A(h),{}),k[g]=e[h];else throw Error(a+" missing "+h);b=c?c.apply(e[a],k):void 0;if(a)if(f&&f.exports!==i&&f.exports!==e[a])e[a]=f.exports;else if(b!==i||!j)e[a]=b}else a&&(e[a]=c)};requirejs=require=g=function(a,b,c,e,f){if("string"===typeof a)return p[a]?p[a](b):r(u(a,b).f);if(!a.splice){j=a;j.deps&&g(j.deps,j.callback);if(!b)return;b.splice?(a=b,b=c,c=null):a=i}b=b||function(){};"function"===typeof c&&(c=e,e=f);e?s(i,a,b,c):
setTimeout(function(){s(i,a,b,c)},4);return g};g.config=function(a){return g(a)};requirejs._defined=e;define=function(a,b,c){b.splice||(c=b,b=[]);!l.call(e,a)&&!l.call(m,a)&&(m[a]=[a,b,c])};define.amd={jQuery:!0}})();