(function(s){function l(c,f){return(Math.abs(c.r-f.r)+Math.abs(c.g-f.g)+Math.abs(c.b-f.b))/3}var w=1,g={red:255,green:0,blue:255,alpha:255},j={flat:function(){return{r:g.red,g:g.green,b:g.blue,a:g.alpha}},movement:function(c,f){return{r:(f.r*(g.red/255)+g.red)/2,g:(f.g*(g.green/255)+g.green)/2,b:(f.b*(g.blue/255)+g.blue)/2,a:f.a}},flatDifferenceIntensity:function(c,f){return{r:g.red,g:g.green,b:g.blue,a:l(c,f)}},movementDifferenceIntensity:function(c,f){var q=0.8*(l(c,f)/255);return{r:(1-q)*f.r*(g.red/
255)+q*g.red,g:(1-q)*f.g*(g.green/255)+q*g.green,b:(1-q)*f.b*(g.blue/255)+q*g.blue,a:f.a}}},B=j.flat,x=1200,H=/^https?:\/\//,I=RegExp("^https?://"+document.domain);s.resemble=function(c){function f(){var a=m.length,e;for(e=0;e<a;e++)if("function"===typeof m[e])m[e](k)}function g(a,e,b){var d,p;for(d=0;d<a;d++)for(p=0;p<e;p++)b(d,p)}function j(a,e){var b,d=new Image;H.test(a)&&!I.test(a)&&d.setAttribute("crossorigin","anonymous");d.onload=function(){var a=document.createElement("canvas"),b=d.width,
f=d.height;a.width=b;a.height=f;a.getContext("2d").drawImage(d,0,0,b,f);a=a.getContext("2d").getImageData(0,0,b,f);h.push(a);e(a,b,f)};if("string"===typeof a){if(d.src=a,d.complete)d.onload()}else"undefined"!==typeof a.data&&"number"===typeof a.width&&"number"===typeof a.height?(h.push(a),e(a,a.width,a.height)):(b=new FileReader,b.onload=function(a){d.src=a.target.result},b.readAsDataURL(a))}function r(a,e,b){var d=Math.abs(a-e);return"undefined"===typeof a||"undefined"===typeof e?!1:a===e?!0:d<i[b]?
!0:!1}function s(a,e){var b=r(a.a,e.a,"alpha");return r(a.brightness,e.brightness,"minBrightness")&&b}function l(a,e,b){var a=a/255,e=e/255,b=b/255,d=Math.max(a,e,b),f=Math.min(a,e,b),g;if(d==f)g=0;else{f=d-f;switch(d){case a:g=(e-b)/f+(e<b?6:0);break;case e:g=(b-a)/f+2;break;case b:g=(a-e)/f+4}g/=6}return g}function C(a,e,b,d,f,g){var c,h,t,D=0,k=0,j=0;a.h=l(a.r,a.g,a.b);for(h=-1;1>=h;h++)for(t=-1;1>=t;t++)if(!(0===h&&0===t)&&(c=4*((d+t)*g+(f+h)),c=z(e,c,b),null!==c)){u(c);c.h=l(c.r,c.g,c.b);Math.abs(a.brightness-
c.brightness)>i.maxBrightness&&D++;var J=a.g===c.g,K=a.b===c.b;a.r===c.r&&(J&&K)&&j++;0.3<Math.abs(c.h-a.h)&&k++;if(1<k||1<D)return!0}return 2>j?!0:!1}function A(a,e,b,d){b=B(b,d);a[e]=b.r;a[e+1]=b.g;a[e+2]=b.b;a[e+3]=b.a}function E(a,e,b){a[e]=b.brightness;a[e+1]=b.brightness;a[e+2]=b.brightness;a[e+3]=b.a*w}function z(a,e){var b,d,f,c;b=a[e];return"undefined"!==typeof b?(d=a[e+1],f=a[e+2],c=a[e+3],b={r:b,g:d,b:f,a:c}):null}function u(a){a.brightness=0.3*a.r+0.59*a.g+0.11*a.b}function F(a,e,b){var d;
return a.height<b||a.width<e?(d=document.createElement("canvas"),d.width=e,d.height=b,d=d.getContext("2d"),d.putImageData(a,0,0),d.getImageData(0,0,e,b)):a}function G(a){var e,b="function"===typeof a;b||(e=a);var d={ignoreNothing:function(){i.red=16;i.green=16;i.blue=16;i.alpha=16;i.minBrightness=16;i.maxBrightness=240;y=v=!1;b&&a();return d},ignoreAntialiasing:function(){i.red=32;i.green=32;i.blue=32;i.alpha=32;i.minBrightness=64;i.maxBrightness=96;v=!0;y=!1;b&&a();return d},ignoreColors:function(){i.alpha=
16;i.minBrightness=16;i.maxBrightness=240;v=!1;y=!0;b&&a();return d},repaint:function(){b&&a();return d},onComplete:function(a){m.push(a);a=function(){var a=c,b=e,d=function(){var a,b;if(2===h.length){a=h[0].width>h[1].width?h[0].width:h[1].width;b=h[0].height>h[1].height?h[0].height:h[1].height;k.isSameDimensions=h[0].width===h[1].width&&h[0].height===h[1].height?!0:!1;k.dimensionDifference={width:h[0].width-h[1].width,height:h[0].height-h[1].height};var e=F(h[0],a,b),d=F(h[1],a,b),c=document.createElement("canvas"),
i=e.data,j=d.data;c.width=a;c.height=b;var n=c.getContext("2d"),p=n.createImageData(a,b),o=p.data,l=0,e=Date.now(),m;if(x&&v&&(a>x||b>x))m=6;g(b,a,function(b,e){if(!m||!(0===b%m||0===e%m)){var c=4*(b*a+e),d=z(i,c,1),f=z(j,c,2);if(!(null===d||null===f))if(y)u(d),u(f),s(d,f)?E(o,c,f):(A(o,c,d,f),l++);else{var g=r(d.r,f.r,"red"),h=r(d.g,f.g,"green"),k=r(d.b,f.b,"blue"),n=r(d.a,f.a,"alpha");g&&h&&k&&n?(o[c]=d.r,o[c+1]=d.g,o[c+2]=d.b,o[c+3]=d.a*w):v&&(u(d),u(f),C(d,i,1,b,e,a)||C(f,j,2,b,e,a))?s(d,f)?E(o,
c,f):(A(o,c,d,f),l++):(A(o,c,d,f),l++)}}});k.misMatchPercentage=(100*(l/(b*a))).toFixed(2);k.analysisTime=Date.now()-e;k.getImageDataUrl=function(a){var b=0;a&&(n.font="12px sans-serif",b=n.measureText(a).width+4,b>c.width&&(c.width=b),c.height+=22,n.fillStyle="#666",n.fillRect(0,0,c.width,18),n.fillStyle="#fff",n.fillRect(0,18,c.width,4),n.fillStyle="#fff",n.textBaseline="top",n.font="12px sans-serif",n.fillText(a,2,1),b=22);n.putImageData(p,0,b);return c.toDataURL("image/png")};f()}};h=[];j(a,d);
j(b,d)};a();return G(a)}};return d}var k={},h=[],m=[],i={red:16,green:16,blue:16,alpha:16,minBrightness:16,maxBrightness:240},v=!1,y=!1;return{onComplete:function(a){m.push(a);j(c,function(a,b,d){var c=a.data,h=0,i=0,j=0,l=0,m=0;g(d,b,function(a,d){var e=4*(a*b+d),f=c[e],g=c[e+1],e=c[e+2];h++;i+=100*(f/255);j+=100*(g/255);l+=100*(e/255);m+=100*((0.3*f+0.59*g+0.11*e)/255)});k.red=Math.floor(i/h);k.green=Math.floor(j/h);k.blue=Math.floor(l/h);k.brightness=Math.floor(m/h);f()})},compareTo:function(a){return G(a)}}};
s.resemble.outputSettings=function(c){var f;if(c.errorColor)for(f in c.errorColor)g[f]=void 0===c.errorColor[f]?g[f]:c.errorColor[f];c.errorType&&j[c.errorType]&&(B=j[c.errorType]);w=isNaN(Number(c.transparency))?w:c.transparency;void 0!==c.largeImageThreshold&&(x=c.largeImageThreshold);return this}})(this);